version: '2'
services:
  redis1:
    build:
      context: ./docker/redis
    environment:
      REDIS_PORT: 7000
    network_mode: "host"

  redis2:
    build:
      context: ./docker/redis
    environment:
      REDIS_PORT: 7001
    network_mode: "host"

  redis3:
    build:
      context: ./docker/redis
    environment:
      REDIS_PORT: 7002
    network_mode: "host"

  redis4:
    build:
      context: ./docker/redis
    environment:
      REDIS_PORT: 7003
    network_mode: "host"

  redis5:
    build:
      context: ./docker/redis
    environment:
      REDIS_PORT: 7004
    network_mode: "host"

  redis6:
    build:
      context: ./docker/redis
    environment:
      REDIS_PORT: 7005
    network_mode: "host"

  redis-cluster-setting:
    build:
      context: ./docker/redis-cluster-setting
    environment:
      REDIS_NODES: "127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005"
      REDIS_REPLICAS: 1